### ISSUE TITLE
User - addUser - Seleccionar empresa

### ISSUE THREAD

**Issue by ax3l98** [XIKDEV/X-NOM-35-FRONT#33]
Agregar componente "Select" en el formulario para crear usuario con el siguiente comportamiento:

- Permitirá seleccionar empresa unicamente si el rol no es "Desarrollador" o "Super admin" (estos roles se sobre entienden que pertenecen a Xik)
- Se ocultará si el rol es "Desarrollador" o "Super admin"
- Mostrará el listado de empresas existentes registradas en Nom-035
- No permitirá crear nuevas empresas

**Comment by XIKDEV** [comment]
Se cerrara por proyecto depreciado
